services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Exposes the API on port 8080
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: always
    networks:
      - cors-network  # Reference the defined network

  frontend:
    image: nginx:alpine
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8081:80"  # Exposes the frontend on port 8081
    networks:
      - cors-network  # Reference the defined network

# Define the network
networks:
  cors-network:
    driver: bridge  # Use the default bridge driver for networking
